# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.interfaces.grpc import broker_pb2 as broker__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in broker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageBrokerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeclareExchange = channel.unary_unary(
                '/broker.MessageBroker/DeclareExchange',
                request_serializer=broker__pb2.ExchangeRequest.SerializeToString,
                response_deserializer=broker__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.DeclareQueue = channel.unary_unary(
                '/broker.MessageBroker/DeclareQueue',
                request_serializer=broker__pb2.QueueRequest.SerializeToString,
                response_deserializer=broker__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.BindQueue = channel.unary_unary(
                '/broker.MessageBroker/BindQueue',
                request_serializer=broker__pb2.BindRequest.SerializeToString,
                response_deserializer=broker__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/broker.MessageBroker/Publish',
                request_serializer=broker__pb2.PublishRequest.SerializeToString,
                response_deserializer=broker__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.Consume = channel.unary_stream(
                '/broker.MessageBroker/Consume',
                request_serializer=broker__pb2.ConsumeRequest.SerializeToString,
                response_deserializer=broker__pb2.Message.FromString,
                _registered_method=True)


class MessageBrokerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeclareExchange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclareQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageBrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeclareExchange': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareExchange,
                    request_deserializer=broker__pb2.ExchangeRequest.FromString,
                    response_serializer=broker__pb2.ActionResponse.SerializeToString,
            ),
            'DeclareQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareQueue,
                    request_deserializer=broker__pb2.QueueRequest.FromString,
                    response_serializer=broker__pb2.ActionResponse.SerializeToString,
            ),
            'BindQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.BindQueue,
                    request_deserializer=broker__pb2.BindRequest.FromString,
                    response_serializer=broker__pb2.ActionResponse.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=broker__pb2.PublishRequest.FromString,
                    response_serializer=broker__pb2.PublishResponse.SerializeToString,
            ),
            'Consume': grpc.unary_stream_rpc_method_handler(
                    servicer.Consume,
                    request_deserializer=broker__pb2.ConsumeRequest.FromString,
                    response_serializer=broker__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broker.MessageBroker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('broker.MessageBroker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageBroker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeclareExchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.MessageBroker/DeclareExchange',
            broker__pb2.ExchangeRequest.SerializeToString,
            broker__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeclareQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.MessageBroker/DeclareQueue',
            broker__pb2.QueueRequest.SerializeToString,
            broker__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.MessageBroker/BindQueue',
            broker__pb2.BindRequest.SerializeToString,
            broker__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.MessageBroker/Publish',
            broker__pb2.PublishRequest.SerializeToString,
            broker__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/broker.MessageBroker/Consume',
            broker__pb2.ConsumeRequest.SerializeToString,
            broker__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
