# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: broker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'broker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62roker.proto\x12\x06\x62roker\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n\x0f\x45xchangeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.broker.ExchangeType\"\x1c\n\x0cQueueRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"M\n\x0b\x42indRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\x12\x15\n\rexchange_name\x18\x02 \x01(\t\x12\x13\n\x0b\x62inding_key\x18\x03 \x01(\t\"M\n\x0ePublishRequest\x12\x15\n\rexchange_name\x18\x01 \x01(\t\x12\x13\n\x0brouting_key\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\"j\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0brouting_key\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"$\n\x0e\x43onsumeRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\"5\n\x0fPublishResponse\x12\x0e\n\x06stored\x18\x01 \x01(\x08\x12\x12\n\nmessage_id\x18\x02 \x01(\t\"8\n\x0e\x41\x63tionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t*1\n\x0c\x45xchangeType\x12\n\n\x06\x44IRECT\x10\x00\x12\n\n\x06\x46\x41NOUT\x10\x01\x12\t\n\x05TOPIC\x10\x02\x32\xbd\x02\n\rMessageBroker\x12\x42\n\x0f\x44\x65\x63lareExchange\x12\x17.broker.ExchangeRequest\x1a\x16.broker.ActionResponse\x12<\n\x0c\x44\x65\x63lareQueue\x12\x14.broker.QueueRequest\x1a\x16.broker.ActionResponse\x12\x38\n\tBindQueue\x12\x13.broker.BindRequest\x1a\x16.broker.ActionResponse\x12:\n\x07Publish\x12\x16.broker.PublishRequest\x1a\x17.broker.PublishResponse\x12\x34\n\x07\x43onsume\x12\x16.broker.ConsumeRequest\x1a\x0f.broker.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'broker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXCHANGETYPE']._serialized_start=573
  _globals['_EXCHANGETYPE']._serialized_end=622
  _globals['_EXCHANGEREQUEST']._serialized_start=57
  _globals['_EXCHANGEREQUEST']._serialized_end=124
  _globals['_QUEUEREQUEST']._serialized_start=126
  _globals['_QUEUEREQUEST']._serialized_end=154
  _globals['_BINDREQUEST']._serialized_start=156
  _globals['_BINDREQUEST']._serialized_end=233
  _globals['_PUBLISHREQUEST']._serialized_start=235
  _globals['_PUBLISHREQUEST']._serialized_end=312
  _globals['_MESSAGE']._serialized_start=314
  _globals['_MESSAGE']._serialized_end=420
  _globals['_CONSUMEREQUEST']._serialized_start=422
  _globals['_CONSUMEREQUEST']._serialized_end=458
  _globals['_PUBLISHRESPONSE']._serialized_start=460
  _globals['_PUBLISHRESPONSE']._serialized_end=513
  _globals['_ACTIONRESPONSE']._serialized_start=515
  _globals['_ACTIONRESPONSE']._serialized_end=571
  _globals['_MESSAGEBROKER']._serialized_start=625
  _globals['_MESSAGEBROKER']._serialized_end=942
# @@protoc_insertion_point(module_scope)
