drop table if exists orders;
drop table if exists accounts;

create table accounts (
    id int primary key,
    owner_name varchar(50) not null,
    balance int not null
);

create table orders (
    id int generated by default as identity primary key,
    customer_name varchar(50) not null,
    amount int not null,
    status varchar(20) not null
);

insert into accounts (id, owner_name, balance) values
    (1, 'ivan', 1000),
    (2, 'anna', 1500);

insert into orders (customer_name, amount, status) values
    ('ivan', 100, 'new'),
    ('anna', 200, 'new'),
    ('petr', 300, 'paid');
